[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ghost_market = "5oCgPmgHbb5h1qv3tkyVSW21Zjw75NzYEb5XYjUiqGxa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deploy-wallet.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
